# Generated by Django 6.1.1 on 2026-10-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('sport_type', models.CharField(max_length=20)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
