# Generated by Django 6.1.1 on 2026-09-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('instructor', 'Instructor'), ('owner', 'Facility Owner')], default='player', max_length=20),
        ),
    ]
