# Generated by Django 6.1.1 on 2026-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10),
        ),
    ]
